"""
ReportLab PDF Generation Subsystem for QNetra.

Generates professional, enterprise-grade cybersecurity assessment reports:
- Executive Cryptographic Assessment (concise leadership report)
- PQC Migration Plan (prioritized remediation and replacement roadmap)
- Complete Cryptographic Assessment (comprehensive technical report)
- Custom PDF Export (user-selected sections)
"""

from __future__ import annotations

import io
from typing import Any, List

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.pdfgen import canvas
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

from backend.reports.data import ReportData

# Printable canvas width: 612 - 72 = 540 pt
PAGE_WIDTH = 540

# Enterprise Color Palette
COLOR_PRIMARY = colors.HexColor("#0f172a")    # Slate-900
COLOR_SECONDARY = colors.HexColor("#334155")  # Slate-700
COLOR_ACCENT = colors.HexColor("#2563eb")     # Blue-600
COLOR_MUTED = colors.HexColor("#64748b")      # Slate-500
COLOR_BORDER = colors.HexColor("#cbd5e1")     # Slate-300
COLOR_BG_LIGHT = colors.HexColor("#f8fafc")   # Slate-50
COLOR_BG_ALT = colors.HexColor("#f1f5f9")     # Slate-100

# Severity Colors
COLOR_CRITICAL = colors.HexColor("#dc2626")   # Red-600
COLOR_HIGH = colors.HexColor("#ea580c")       # Orange-600
COLOR_MEDIUM = colors.HexColor("#ca8a04")     # Yellow-600
COLOR_LOW = colors.HexColor("#16a34a")        # Green-600


class NumberedCanvas(canvas.Canvas):
    """
    Two-pass canvas to dynamically compute and draw headers and footers with 'Page X of Y'.
    """
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states: list[dict[str, Any]] = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_chrome(num_pages)
            super().showPage()
        super().save()

    def draw_page_chrome(self, page_count: int):
        self.saveState()

        # Running Header (pages after cover / first page)
        if self._pageNumber > 1:
            self.setFont("Helvetica-Bold", 8)
            self.setFillColor(COLOR_PRIMARY)
            self.drawString(36, 762, "QNetra")
            self.setFont("Helvetica", 8)
            self.setFillColor(COLOR_MUTED)
            self.drawString(72, 762, "|  Cryptographic Assessment & Migration Report")

            self.setStrokeColor(COLOR_BORDER)
            self.setLineWidth(0.5)
            self.line(36, 754, 576, 754)

        # Running Footer (all pages)
        self.setStrokeColor(COLOR_BORDER)
        self.setLineWidth(0.5)
        self.line(36, 42, 576, 42)

        self.setFont("Helvetica-Bold", 7.5)
        self.setFillColor(COLOR_SECONDARY)
        self.drawString(36, 30, "CONFIDENTIAL")
        self.setFont("Helvetica", 7.5)
        self.setFillColor(COLOR_MUTED)
        self.drawString(104, 30, "— Generated by QNetra Cryptographic Discovery Engine")

        page_str = f"Page {self._pageNumber} of {page_count}"
        self.drawRightString(576, 30, page_str)

        self.restoreState()


def get_report_styles():
    base = getSampleStyleSheet()
    styles = {
        "DocTitle": ParagraphStyle(
            "DocTitle",
            parent=base["Normal"],
            fontName="Helvetica-Bold",
            fontSize=18,
            leading=22,
            textColor=COLOR_PRIMARY,
            spaceAfter=4,
        ),
        "DocSubtitle": ParagraphStyle(
            "DocSubtitle",
            parent=base["Normal"],
            fontName="Helvetica",
            fontSize=9.5,
            leading=13,
            textColor=COLOR_MUTED,
            spaceAfter=12,
        ),
        "SectionHeading": ParagraphStyle(
            "SectionHeading",
            parent=base["Normal"],
            fontName="Helvetica-Bold",
            fontSize=12,
            leading=15,
            textColor=COLOR_PRIMARY,
            spaceBefore=14,
            spaceAfter=6,
            keepWithNext=True,
        ),
        "SubSectionHeading": ParagraphStyle(
            "SubSectionHeading",
            parent=base["Normal"],
            fontName="Helvetica-Bold",
            fontSize=10,
            leading=13,
            textColor=COLOR_SECONDARY,
            spaceBefore=10,
            spaceAfter=4,
            keepWithNext=True,
        ),
        "BodyText": ParagraphStyle(
            "BodyText",
            parent=base["Normal"],
            fontName="Helvetica",
            fontSize=8.5,
            leading=11.5,
            textColor=COLOR_SECONDARY,
            spaceAfter=6,
        ),
        "BodyBold": ParagraphStyle(
            "BodyBold",
            parent=base["Normal"],
            fontName="Helvetica-Bold",
            fontSize=8.5,
            leading=11.5,
            textColor=COLOR_PRIMARY,
        ),
        "TableHead": ParagraphStyle(
            "TableHead",
            parent=base["Normal"],
            fontName="Helvetica-Bold",
            fontSize=7.5,
            leading=9.5,
            textColor=COLOR_PRIMARY,
        ),
        "TableCell": ParagraphStyle(
            "TableCell",
            parent=base["Normal"],
            fontName="Helvetica",
            fontSize=7.5,
            leading=9.5,
            textColor=COLOR_SECONDARY,
        ),
        "TableCellBold": ParagraphStyle(
            "TableCellBold",
            parent=base["Normal"],
            fontName="Helvetica-Bold",
            fontSize=7.5,
            leading=9.5,
            textColor=COLOR_PRIMARY,
        ),
        "TableCode": ParagraphStyle(
            "TableCode",
            parent=base["Normal"],
            fontName="Courier",
            fontSize=7,
            leading=8.5,
            textColor=COLOR_PRIMARY,
        ),
        "KpiValue": ParagraphStyle(
            "KpiValue",
            parent=base["Normal"],
            fontName="Helvetica-Bold",
            fontSize=14,
            leading=17,
            alignment=1,  # Center
            textColor=COLOR_PRIMARY,
        ),
        "KpiLabel": ParagraphStyle(
            "KpiLabel",
            parent=base["Normal"],
            fontName="Helvetica",
            fontSize=7,
            leading=9,
            alignment=1,  # Center
            textColor=COLOR_MUTED,
        ),
    }
    return styles


GLOBAL_STYLES = get_report_styles()


def safe_p(text: Any, style: ParagraphStyle) -> Paragraph:
    """Helper that converts text to string and never passes None to Paragraph."""
    if text is None:
        return Paragraph("", style)
    return Paragraph(str(text), style)


def get_severity_color(sev: str) -> colors.Color:
    s = (sev or "").upper()
    if s == "CRITICAL":
        return COLOR_CRITICAL
    if s == "HIGH":
        return COLOR_HIGH
    if s == "MEDIUM":
        return COLOR_MEDIUM
    return COLOR_LOW


def make_header_block(title: str, subtitle: str, data: ReportData, styles: dict) -> list:
    """Creates the standardized top cover/identity banner."""
    story = [
        safe_p(title, styles["DocTitle"]),
        safe_p(subtitle, styles["DocSubtitle"]),
    ]

    # Meta Table: Target, Completed Date, Scan ID, Status
    sev_color = get_severity_color(data.overall_severity)
    meta_data = [
        [
            safe_p("<b>Target:</b>", styles["TableCellBold"]),
            safe_p(data.target_name, styles["TableCell"]),
            safe_p("<b>Scan Date:</b>", styles["TableCellBold"]),
            safe_p(data.completed_at_str, styles["TableCell"]),
        ],
        [
            safe_p("<b>Scan ID:</b>", styles["TableCellBold"]),
            safe_p(data.scan_id[:18] + "...", styles["TableCode"]),
            safe_p("<b>Overall Posture:</b>", styles["TableCellBold"]),
            safe_p(
                f"<font color='{sev_color.hexval()}'><b>{data.overall_severity} ({data.overall_risk_score:.1f}/100)</b></font>",
                styles["TableCell"],
            ),
        ],
    ]
    t = Table(meta_data, colWidths=[65, 205, 95, 175])
    t.setStyle(
        TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), COLOR_BG_LIGHT),
            ("BOX", (0, 0), (-1, -1), 0.5, COLOR_BORDER),
            ("INNERGRID", (0, 0), (-1, -1), 0.5, COLOR_BORDER),
            ("TOPPADDING", (0, 0), (-1, -1), 4),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ("LEFTPADDING", (0, 0), (-1, -1), 6),
            ("RIGHTPADDING", (0, 0), (-1, -1), 6),
        ])
    )
    story.append(t)
    story.append(Spacer(1, 10))
    return story


def make_kpi_cards(data: ReportData, styles: dict) -> Table:
    """Builds the 6-metric summary KPI grid."""
    row_vals = [
        safe_p(f"{data.overall_risk_score:.1f}", styles["KpiValue"]),
        safe_p(str(data.total_assets), styles["KpiValue"]),
        safe_p(str(data.shor_vulnerable_count), styles["KpiValue"]),
        safe_p(str(data.grover_impacted_count), styles["KpiValue"]),
        safe_p(str(data.direct_pqc_count + data.classical_upgrade_count), styles["KpiValue"]),
        safe_p(str(data.quantum_resistant_count), styles["KpiValue"]),
    ]
    row_labels = [
        safe_p("Risk Score", styles["KpiLabel"]),
        safe_p("Total Assets", styles["KpiLabel"]),
        safe_p("Shor Vulnerable", styles["KpiLabel"]),
        safe_p("Grover Impacted", styles["KpiLabel"]),
        safe_p("Migration Required", styles["KpiLabel"]),
        safe_p("Quantum Resistant", styles["KpiLabel"]),
    ]
    card_data = [row_vals, row_labels]
    w = PAGE_WIDTH / 6.0
    t = Table(card_data, colWidths=[w] * 6)
    t.setStyle(
        TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), COLOR_BG_LIGHT),
            ("BOX", (0, 0), (-1, -1), 0.5, COLOR_BORDER),
            ("INNERGRID", (0, 0), (-1, -1), 0.5, COLOR_BORDER),
            ("TOPPADDING", (0, 0), (-1, 0), 6),
            ("BOTTOMPADDING", (0, 0), (-1, 0), 2),
            ("TOPPADDING", (0, 1), (-1, 1), 2),
            ("BOTTOMPADDING", (0, 1), (-1, 1), 6),
            ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ])
    )
    return t


def make_exposures_table(data: ReportData, styles: dict, limit: int = 8) -> Table:
    """Table of top high-risk assets."""
    rows = [
        [
            safe_p("Algorithm", styles["TableHead"]),
            safe_p("Primitive", styles["TableHead"]),
            safe_p("Risk", styles["TableHead"]),
            safe_p("Threat", styles["TableHead"]),
            safe_p("Urgency", styles["TableHead"]),
            safe_p("Target Replacement", styles["TableHead"]),
            safe_p("Location", styles["TableHead"]),
        ]
    ]
    count = 0
    for a in data.assets:
        sev = a.get("risk_severity") or "LOW"
        if sev not in ("CRITICAL", "HIGH") and count >= limit:
            continue
        count += 1
        sev_color = get_severity_color(sev)
        algo = a.get("algorithm") or "Unknown"
        prim = (a.get("primitive_type") or "UNKNOWN")[:18]
        threat = a.get("quantum_threat_type") or "NONE"
        urg = a.get("mosca_urgency") or "LOW"
        rec_algo = a.get("recommended_algorithm") or "N/A"
        loc_str = a.get("location_str") or "N/A"
        if len(loc_str) > 35:
            loc_str = "..." + loc_str[-32:]

        rows.append([
            safe_p(f"<b>{algo}</b>", styles["TableCellBold"]),
            safe_p(prim, styles["TableCell"]),
            safe_p(f"<font color='{sev_color.hexval()}'><b>{sev} ({a.get('risk_score', 0)})</b></font>", styles["TableCell"]),
            safe_p(threat, styles["TableCell"]),
            safe_p(urg, styles["TableCell"]),
            safe_p(rec_algo, styles["TableCellBold"]),
            safe_p(loc_str, styles["TableCode"]),
        ])
        if count >= limit:
            break

    if len(rows) == 1:
        rows.append([safe_p("No critical or high-risk cryptographic exposures discovered.", styles["TableCell"])] + [safe_p("", styles["TableCell"])] * 6)

    col_widths = [80, 75, 70, 60, 55, 90, 110]
    t = Table(rows, colWidths=col_widths)
    t.setStyle(
        TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), COLOR_BG_ALT),
            ("GRID", (0, 0), (-1, -1), 0.5, COLOR_BORDER),
            ("TOPPADDING", (0, 0), (-1, -1), 3),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
            ("LEFTPADDING", (0, 0), (-1, -1), 4),
            ("RIGHTPADDING", (0, 0), (-1, -1), 4),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ])
    )
    return t


def make_migration_table(data: ReportData, styles: dict, limit: int = 15) -> Table:
    """Table of prioritized migration actions."""
    rows = [
        [
            safe_p("Current Algorithm", styles["TableHead"]),
            safe_p("Category", styles["TableHead"]),
            safe_p("Replacement", styles["TableHead"]),
            safe_p("PQC Standard", styles["TableHead"]),
            safe_p("Urgency", styles["TableHead"]),
            safe_p("Complexity", styles["TableHead"]),
            safe_p("Source Location", styles["TableHead"]),
        ]
    ]

    actions = data.migration_actions[:limit]
    for m in actions:
        urg = m.get("urgency") or "LOW"
        urg_color = get_severity_color(urg)
        cur_algo = m.get("current_algorithm") or "Unknown"
        cat = (m.get("migration_category") or "").replace("_", " ")
        rec_algo = m.get("recommended_algorithm") or "N/A"
        pqc_std = m.get("pqc_standard") or "N/A"
        comp = m.get("migration_complexity") or "MEDIUM"
        loc_str = m.get("location_str") or "N/A"
        if len(loc_str) > 35:
            loc_str = "..." + loc_str[-32:]

        rows.append([
            safe_p(f"<b>{cur_algo}</b>", styles["TableCellBold"]),
            safe_p(cat, styles["TableCell"]),
            safe_p(f"<b>{rec_algo}</b>", styles["TableCellBold"]),
            safe_p(pqc_std, styles["TableCell"]),
            safe_p(f"<font color='{urg_color.hexval()}'><b>{urg}</b></font>", styles["TableCell"]),
            safe_p(comp, styles["TableCell"]),
            safe_p(loc_str, styles["TableCode"]),
        ])

    if len(rows) == 1:
        rows.append([safe_p("No migration actions required.", styles["TableCell"])] + [safe_p("", styles["TableCell"])] * 6)

    col_widths = [90, 85, 90, 75, 55, 55, 90]
    t = Table(rows, colWidths=col_widths)
    t.setStyle(
        TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), COLOR_BG_ALT),
            ("GRID", (0, 0), (-1, -1), 0.5, COLOR_BORDER),
            ("TOPPADDING", (0, 0), (-1, -1), 3),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
            ("LEFTPADDING", (0, 0), (-1, -1), 4),
            ("RIGHTPADDING", (0, 0), (-1, -1), 4),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ])
    )
    return t


def build_executive_pdf(data: ReportData) -> bytes:
    """
    Generates the Executive Cryptographic Assessment PDF.
    A concise, leadership-focused document (2-3 pages).
    """
    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf,
        pagesize=letter,
        leftMargin=36,
        rightMargin=36,
        topMargin=44,
        bottomMargin=44,
    )
    styles = GLOBAL_STYLES
    story = []

    # Title & Identity Banner
    story.extend(
        make_header_block(
            "Executive Cryptographic Assessment",
            "Concise Security Posture, Quantum Threat Exposure & Prioritized Remediation Roadmap",
            data,
            styles,
        )
    )

    # 1. Executive Summary & KPIs
    story.append(safe_p("1. Executive Summary", styles["SectionHeading"]))
    story.append(
        safe_p(
            f"QNetra conducted a static cryptographic discovery and post-quantum vulnerability assessment on "
            f"<b>{data.target_name}</b>. The assessment discovered a total of <b>{data.total_assets}</b> cryptographic assets. "
            f"The overall cryptographic risk posture is assessed as <b>{data.overall_severity}</b> "
            f"with a composite risk index of <b>{data.overall_risk_score:.1f}/100</b>. "
            f"A total of <b>{data.shor_vulnerable_count}</b> assets rely on asymmetric primitives vulnerable to Shor's algorithm, "
            f"and <b>{data.direct_pqc_count + data.classical_upgrade_count}</b> assets require scheduled migration.",
            styles["BodyText"],
        )
    )
    story.append(make_kpi_cards(data, styles))
    story.append(Spacer(1, 10))

    # 2. Key Exposures
    story.append(safe_p("2. Critical & High Cryptographic Exposures", styles["SectionHeading"]))
    story.append(
        safe_p(
            "The following assets represent the highest immediate risk due to vulnerable algorithms, "
            "exposure to quantum cryptanalysis (Shor/Grover), or impending Harvest-Now-Decrypt-Later (HNDL) deadlines:",
            styles["BodyText"],
        )
    )
    story.append(make_exposures_table(data, styles, limit=6))
    story.append(Spacer(1, 10))

    # 3. Quantum Exposure Breakdown (Shor & Grover)
    story.append(safe_p("3. Quantum Exposure & Vulnerability Breakdown", styles["SectionHeading"]))
    vuln_algos = sorted({a["algorithm"] for a in data.assets if a.get("quantum_vulnerable")})
    vuln_algos_str = ", ".join(vuln_algos) if vuln_algos else "None"
    story.append(
        safe_p(
            f"<b>Asymmetric Vulnerability (Shor's Algorithm):</b> Discovered <b>{data.shor_vulnerable_count}</b> assets. "
            f"Shor's algorithm running on a cryptanalytically relevant quantum computer (CRQC) completely breaks "
            f"discrete logarithm and integer factorization problems. Affected algorithms: <b>{vuln_algos_str}</b>.<br/>"
            f"<b>Symmetric Degradation (Grover's Algorithm):</b> Discovered <b>{data.grover_impacted_count}</b> assets with reduced bit-security.<br/>"
            f"<b>Quantum Resistant:</b> <b>{data.quantum_resistant_count}</b> assets meet post-quantum or high-bit symmetric standards.",
            styles["BodyText"],
        )
    )
    story.append(Spacer(1, 8))

    # 4. Mosca / HNDL Assessment Summary
    story.append(safe_p("4. Mosca Theorem & HNDL Timeline Urgency", styles["SectionHeading"]))
    x_val = data.mosca_parameters.get("data_shelf_life_years_x", 10)
    y_val = data.mosca_parameters.get("migration_time_years_y", 3)
    z_val = data.mosca_parameters.get("quantum_threat_horizon_years_z", 10)
    story.append(
        safe_p(
            f"Under Mosca's Inequality (<i>X + Y &gt; Z</i>), if required data shelf-life (<i>X = {x_val}y</i>) plus "
            f"migration duration (<i>Y = {y_val}y</i>) exceeds quantum arrival (<i>Z = {z_val}y</i>), encrypted communications "
            f"are already compromised today via Harvest-Now-Decrypt-Later (HNDL) adversary collection. "
            f"<b>{data.mosca_triggered_count}</b> assets currently exceed the migration condition.",
            styles["BodyText"],
        )
    )
    story.append(Spacer(1, 8))

    # 5. Migration Strategy & Priorities
    story.append(safe_p("5. Migration Strategy Summary", styles["SectionHeading"]))
    strat_text = (
        f"• <b>Direct PQC Migration:</b> <b>{data.direct_pqc_count}</b> assets (immediate replacement with NIST FIPS 203/204/205 standards)<br/>"
        f"• <b>Hybrid Schemes:</b> <b>{data.hybrid_count}</b> assets (FIPS compliant dual classical/quantum combinations)<br/>"
        f"• <b>Classical Upgrade:</b> <b>{data.classical_upgrade_count}</b> assets (replace deprecated/weak algorithms)<br/>"
        f"• <b>No Migration Required:</b> <b>{data.no_migration_required_count}</b> assets (already post-quantum or adequate security)"
    )
    story.append(safe_p(strat_text, styles["BodyText"]))
    story.append(Spacer(1, 10))

    # 6. Strategic Next Steps & Evidence Traceability
    story.append(safe_p("6. Recommendations & Evidence Traceability", styles["SectionHeading"]))
    story.append(
        safe_p(
            f"All findings in this assessment are deterministically traceable to <b>{len(data.findings)}</b> concrete scanner discoveries "
            f"and <b>{data.cbom_component_count}</b> CycloneDX 1.6 CBOM components. Recommended leadership actions:<br/>"
            f"1. Prioritize replacement of Shor-vulnerable public key algorithms (RSA/ECDSA/DH) in external-facing endpoints.<br/>"
            f"2. Mandate adoption of NIST FIPS 203 (ML-KEM) for key exchange and FIPS 204 (ML-DSA) for digital signatures.<br/>"
            f"3. Establish a Cryptographic Bill of Materials (CBOM) baseline in CI/CD pipelines to prevent reintroduction of legacy crypto.",
            styles["BodyText"],
        )
    )

    doc.build(story, canvasmaker=NumberedCanvas)
    return buf.getvalue()


def build_migration_pdf(data: ReportData) -> bytes:
    """
    Generates the PQC Migration Plan PDF.
    Technical roadmap focusing on prioritized replacements and NIST standard alignments.
    """
    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf,
        pagesize=letter,
        leftMargin=36,
        rightMargin=36,
        topMargin=44,
        bottomMargin=44,
    )
    styles = GLOBAL_STYLES
    story = []

    # Title & Identity Banner
    story.extend(
        make_header_block(
            "PQC Migration Plan",
            "Prioritized Post-Quantum Cryptographic Remediation Roadmap & Replacement Actions",
            data,
            styles,
        )
    )

    # 1. Executive Roadmap Summary
    story.append(safe_p("1. Migration Scope & Urgency Breakdown", styles["SectionHeading"]))
    story.append(
        safe_p(
            f"This migration plan specifies required remediation steps for <b>{data.direct_pqc_count + data.classical_upgrade_count}</b> "
            f"actionable cryptographic components discovered in <b>{data.target_name}</b>. "
            f"Prioritization is ordered by composite risk score, quantum vulnerability tier, and Mosca HNDL urgency.",
            styles["BodyText"],
        )
    )

    # Strategy counts table
    strat_data = [
        [
            safe_p("Direct PQC", styles["TableHead"]),
            safe_p("Hybrid Scheme", styles["TableHead"]),
            safe_p("Classical Upgrade", styles["TableHead"]),
            safe_p("No Migration", styles["TableHead"]),
        ],
        [
            safe_p(f"<b>{data.direct_pqc_count}</b>", styles["KpiValue"]),
            safe_p(f"<b>{data.hybrid_count}</b>", styles["KpiValue"]),
            safe_p(f"<b>{data.classical_upgrade_count}</b>", styles["KpiValue"]),
            safe_p(f"<b>{data.no_migration_required_count}</b>", styles["KpiValue"]),
        ],
    ]
    st_table = Table(strat_data, colWidths=[PAGE_WIDTH / 4.0] * 4)
    st_table.setStyle(
        TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), COLOR_BG_LIGHT),
            ("GRID", (0, 0), (-1, -1), 0.5, COLOR_BORDER),
            ("TOPPADDING", (0, 0), (-1, -1), 4),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ])
    )
    story.append(st_table)
    story.append(Spacer(1, 10))

    # 2. Prioritized Replacement Actions
    story.append(safe_p("2. Prioritized Replacement Actions", styles["SectionHeading"]))
    story.append(
        safe_p(
            "The table below details recommended PQC replacement algorithms, applicable NIST standards, and source code locations:",
            styles["BodyText"],
        )
    )
    story.append(make_migration_table(data, styles, limit=20))
    story.append(Spacer(1, 10))

    # 3. Post-Quantum Cryptographic Standards Reference
    story.append(safe_p("3. Target Post-Quantum Standards & Guidelines", styles["SectionHeading"]))
    standards_text = (
        "<b>NIST FIPS 203 (ML-KEM):</b> Primary general-purpose key encapsulation mechanism based on CRYSTALS-Kyber. "
        "Recommended for all TLS, SSH, and secure communications replacing RSA and (EC)DH.<br/>"
        "<b>NIST FIPS 204 (ML-DSA):</b> Primary general-purpose digital signature algorithm based on CRYSTALS-Dilithium. "
        "Recommended for code signing, certificates, and authentication replacing RSA-PSS and ECDSA.<br/>"
        "<b>NIST FIPS 205 (SLH-DSA):</b> Stateless hash-based digital signature based on SPHINCS+. "
        "Alternative signature mechanism providing hedge against lattice assumptions for high-assurance firmware signing."
    )
    story.append(safe_p(standards_text, styles["BodyText"]))

    doc.build(story, canvasmaker=NumberedCanvas)
    return buf.getvalue()


def build_technical_pdf(data: ReportData) -> bytes:
    """
    Generates the Complete Technical Report PDF.
    Comprehensive 14-section technical assessment document.
    """
    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf,
        pagesize=letter,
        leftMargin=36,
        rightMargin=36,
        topMargin=44,
        bottomMargin=44,
    )
    styles = GLOBAL_STYLES
    story = []

    # Title & Identity Banner
    story.extend(
        make_header_block(
            "Complete Cryptographic Assessment",
            "Comprehensive Technical Assessment, Inventory, Risk, Quantum Exposure, CBOM & Evidence",
            data,
            styles,
        )
    )

    # 1. Scope & Assessment Metadata
    story.append(safe_p("1. Assessment Metadata & Scope", styles["SectionHeading"]))
    dur_str = f"{data.duration_seconds:.2f}s" if data.duration_seconds else "N/A"
    story.append(
        safe_p(
            f"<b>Target:</b> {data.target_name} ({data.source_type})<br/>"
            f"<b>Source URL / Path:</b> {data.source_url or data.scan_meta.get('target', {}).get('path', 'Local')}<br/>"
            f"<b>Scan Status:</b> {data.status} (Duration: {dur_str})<br/>"
            f"<b>Analysis Engines:</b> Normalization, CBOM Serializer (CycloneDX 1.6), Quantum Risk, Mosca/HNDL, PQC Recommendations",
            styles["BodyText"],
        )
    )
    story.append(Spacer(1, 6))

    # 2. Executive Posture
    story.append(safe_p("2. Executive Summary & Posture", styles["SectionHeading"]))
    story.append(make_kpi_cards(data, styles))
    story.append(Spacer(1, 10))

    # 3. Cryptographic Posture
    story.append(safe_p("3. Cryptographic Inventory Posture", styles["SectionHeading"]))
    algo_counts: dict[str, int] = {}
    for a in data.assets:
        algo_counts[a["algorithm"]] = algo_counts.get(a["algorithm"], 0) + 1
    algo_summary = ", ".join(f"<b>{k}</b>: {v}" for k, v in sorted(algo_counts.items(), key=lambda x: -x[1])[:10])
    story.append(safe_p(f"Discovered {data.total_assets} normalized assets across top algorithms: {algo_summary}.", styles["BodyText"]))
    story.append(Spacer(1, 8))

    # 4. Normalized Cryptographic Assets Table
    story.append(safe_p("4. Normalized Cryptographic Assets", styles["SectionHeading"]))
    asset_rows = [
        [
            safe_p("Asset ID", styles["TableHead"]),
            safe_p("Algorithm", styles["TableHead"]),
            safe_p("Primitive", styles["TableHead"]),
            safe_p("Risk", styles["TableHead"]),
            safe_p("Threat", styles["TableHead"]),
            safe_p("Urgency", styles["TableHead"]),
            safe_p("Primary File & Line", styles["TableHead"]),
        ]
    ]
    for a in data.assets[:25]:
        sev = a.get("risk_severity") or "LOW"
        sev_color = get_severity_color(sev)
        asset_id = (a.get("asset_id") or "")[:10] + "..."
        algo = a.get("algorithm") or "Unknown"
        prim = (a.get("primitive_type") or "UNKNOWN")[:18]
        threat = a.get("quantum_threat_type") or "NONE"
        urg = a.get("mosca_urgency") or "LOW"
        loc_str = a.get("location_str") or "N/A"
        if len(loc_str) > 36:
            loc_str = "..." + loc_str[-33:]
        asset_rows.append([
            safe_p(asset_id, styles["TableCode"]),
            safe_p(f"<b>{algo}</b>", styles["TableCellBold"]),
            safe_p(prim, styles["TableCell"]),
            safe_p(f"<font color='{sev_color.hexval()}'><b>{sev}</b></font>", styles["TableCell"]),
            safe_p(threat, styles["TableCell"]),
            safe_p(urg, styles["TableCell"]),
            safe_p(loc_str, styles["TableCode"]),
        ])
    if len(data.assets) > 25:
        asset_rows.append([safe_p(f"... [{len(data.assets) - 25} more assets in full inventory]", styles["TableCell"])] + [safe_p("", styles["TableCell"])] * 6)

    t_assets = Table(asset_rows, colWidths=[65, 80, 75, 55, 60, 55, 150])
    t_assets.setStyle(
        TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), COLOR_BG_ALT),
            ("GRID", (0, 0), (-1, -1), 0.5, COLOR_BORDER),
            ("TOPPADDING", (0, 0), (-1, -1), 3),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
            ("LEFTPADDING", (0, 0), (-1, -1), 4),
            ("RIGHTPADDING", (0, 0), (-1, -1), 4),
        ])
    )
    story.append(t_assets)
    story.append(Spacer(1, 10))

    # 5. Raw Evidence & Findings Table
    story.append(safe_p("5. Raw Scanner Findings & Evidence", styles["SectionHeading"]))
    find_rows = [
        [
            safe_p("Finding ID", styles["TableHead"]),
            safe_p("Scanner", styles["TableHead"]),
            safe_p("Method", styles["TableHead"]),
            safe_p("Algorithm", styles["TableHead"]),
            safe_p("Confidence", styles["TableHead"]),
            safe_p("Location", styles["TableHead"]),
        ]
    ]
    for f in data.findings[:15]:
        f_id = (f.get("finding_id") or "")[:12] + "..."
        scanner = f.get("scanner_name") or ""
        method = f.get("discovery_method") or ""
        algo = f.get("suspected_algorithm") or ""
        conf = f"{f.get('confidence_score', 0):.2f} ({f.get('confidence_level', '')})"
        loc_str = f.get("location_str") or ""
        if len(loc_str) > 36:
            loc_str = "..." + loc_str[-33:]
        find_rows.append([
            safe_p(f_id, styles["TableCode"]),
            safe_p(scanner, styles["TableCell"]),
            safe_p(method, styles["TableCell"]),
            safe_p(f"<b>{algo}</b>", styles["TableCellBold"]),
            safe_p(conf, styles["TableCell"]),
            safe_p(loc_str, styles["TableCode"]),
        ])
    if len(data.findings) > 15:
        find_rows.append([safe_p(f"... [{len(data.findings) - 15} more findings in full log]", styles["TableCell"])] + [safe_p("", styles["TableCell"])] * 5)

    t_findings = Table(find_rows, colWidths=[75, 80, 75, 85, 80, 145])
    t_findings.setStyle(
        TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), COLOR_BG_ALT),
            ("GRID", (0, 0), (-1, -1), 0.5, COLOR_BORDER),
            ("TOPPADDING", (0, 0), (-1, -1), 3),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
            ("LEFTPADDING", (0, 0), (-1, -1), 4),
            ("RIGHTPADDING", (0, 0), (-1, -1), 4),
        ])
    )
    story.append(t_findings)
    story.append(Spacer(1, 10))

    # 6 & 7. Classical and Quantum Security Analysis
    story.append(safe_p("6. Classical & Quantum Exposure Analysis", styles["SectionHeading"]))
    story.append(
        safe_p(
            f"<b>Classical Security:</b> <b>{data.classically_broken_count}</b> assets are classified as classically broken/weak.<br/>"
            f"<b>Shor Exposure:</b> <b>{data.shor_vulnerable_count}</b> assets vulnerable to polynomial-time quantum attacks.<br/>"
            f"<b>Grover Exposure:</b> <b>{data.grover_impacted_count}</b> assets impacted by quadratic speedup bit-halving.<br/>"
            f"<b>Quantum Resistant:</b> <b>{data.quantum_resistant_count}</b> assets safe against quantum cryptanalysis.",
            styles["BodyText"],
        )
    )
    story.append(Spacer(1, 6))

    # 8 & 9. Risk & Mosca Analysis
    story.append(safe_p("7. Risk Scoring & Mosca/HNDL Analysis", styles["SectionHeading"]))
    p = data.mosca_parameters
    story.append(
        safe_p(
            f"<b>Risk Engine:</b> Overall risk score of <b>{data.overall_risk_score:.1f}/100 ({data.overall_severity})</b>.<br/>"
            f"<b>Mosca Inequality:</b> Parameters: Shelf-life <i>X = {p.get('data_shelf_life_years_x', 10)}y</i>, "
            f"Migration time <i>Y = {p.get('migration_time_years_y', 3)}y</i>, Threat horizon <i>Z = {p.get('quantum_threat_horizon_years_z', 10)}y</i>.<br/>"
            f"Triggered assets: <b>{data.mosca_triggered_count}</b>. HNDL exposed assets: <b>{data.hndl_exposed_count}</b>.",
            styles["BodyText"],
        )
    )
    story.append(Spacer(1, 8))

    # 10 & 11. Migration Recommendations
    story.append(safe_p("8. PQC Migration Recommendations", styles["SectionHeading"]))
    story.append(make_migration_table(data, styles, limit=12))
    story.append(Spacer(1, 10))

    # 12. CBOM Summary
    story.append(safe_p("9. Cryptographic Bill of Materials (CBOM) Summary", styles["SectionHeading"]))
    story.append(
        safe_p(
            f"The scan generated a CycloneDX 1.6 compliant Cryptographic Bill of Materials containing "
            f"<b>{data.cbom_component_count}</b> cryptographic components, including algorithm properties, "
            f"key sizes, curves, implementation libraries, and evidence pointers.",
            styles["BodyText"],
        )
    )
    story.append(Spacer(1, 6))

    # 13 & 14. Evidence Traceability & Technical Appendix
    story.append(safe_p("10. Evidence Traceability & Technical Standards", styles["SectionHeading"]))
    story.append(
        safe_p(
            "Every CryptoAsset in QNetra maintains bi-directional audit links to its originating RawFinding records. "
            "Standards applied: NIST SP 800-57 Part 1 Rev 5 (Key Management), NIST FIPS 203 (ML-KEM), "
            "NIST FIPS 204 (ML-DSA), NIST FIPS 205 (SLH-DSA), and CycloneDX 1.6 CBOM specification.",
            styles["BodyText"],
        )
    )

    doc.build(story, canvasmaker=NumberedCanvas)
    return buf.getvalue()


def build_custom_pdf(data: ReportData, sections: list[str]) -> bytes:
    """
    Generates a customized PDF containing only the requested sections.
    """
    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf,
        pagesize=letter,
        leftMargin=36,
        rightMargin=36,
        topMargin=44,
        bottomMargin=44,
    )
    styles = GLOBAL_STYLES
    story = []

    selected = set(sections)
    subtitle = "Custom Cryptographic Assessment (" + ", ".join(s.capitalize() for s in sections) + ")"
    story.extend(make_header_block("Custom Cryptographic Assessment", subtitle, data, styles))

    if "risk" in selected or "quantum" in selected:
        story.append(safe_p("Executive Posture & Risk Metrics", styles["SectionHeading"]))
        story.append(make_kpi_cards(data, styles))
        story.append(Spacer(1, 10))

    if "assets" in selected:
        story.append(safe_p("Cryptographic Assets Catalog", styles["SectionHeading"]))
        story.append(make_exposures_table(data, styles, limit=15))
        story.append(Spacer(1, 10))

    if "migration" in selected:
        story.append(safe_p("PQC Migration Recommendations", styles["SectionHeading"]))
        story.append(make_migration_table(data, styles, limit=15))
        story.append(Spacer(1, 10))

    if "mosca" in selected:
        story.append(safe_p("Mosca Theorem & HNDL Analysis", styles["SectionHeading"]))
        p = data.mosca_parameters
        story.append(
            safe_p(
                f"Parameters: X={p.get('data_shelf_life_years_x', 10)}y, Y={p.get('migration_time_years_y', 3)}y, Z={p.get('quantum_threat_horizon_years_z', 10)}y.<br/>"
                f"Triggered assets: <b>{data.mosca_triggered_count}</b>. HNDL exposed: <b>{data.hndl_exposed_count}</b>.",
                styles["BodyText"],
            )
        )
        story.append(Spacer(1, 10))

    if "findings" in selected:
        story.append(safe_p("Raw Evidence & Findings", styles["SectionHeading"]))
        find_rows = [
            [
                safe_p("Scanner", styles["TableHead"]),
                safe_p("Method", styles["TableHead"]),
                safe_p("Algorithm", styles["TableHead"]),
                safe_p("Confidence", styles["TableHead"]),
                safe_p("Location", styles["TableHead"]),
            ]
        ]
        for f in data.findings[:15]:
            scanner = f.get("scanner_name") or ""
            method = f.get("discovery_method") or ""
            algo = f.get("suspected_algorithm") or ""
            conf = f"{f.get('confidence_score', 0):.2f}"
            loc_str = f.get("location_str") or ""
            if len(loc_str) > 40:
                loc_str = "..." + loc_str[-37:]
            find_rows.append([
                safe_p(scanner, styles["TableCell"]),
                safe_p(method, styles["TableCell"]),
                safe_p(f"<b>{algo}</b>", styles["TableCellBold"]),
                safe_p(conf, styles["TableCell"]),
                safe_p(loc_str, styles["TableCode"]),
            ])
        t_f = Table(find_rows, colWidths=[90, 80, 100, 70, 200])
        t_f.setStyle(
            TableStyle([
                ("BACKGROUND", (0, 0), (-1, 0), COLOR_BG_ALT),
                ("GRID", (0, 0), (-1, -1), 0.5, COLOR_BORDER),
                ("TOPPADDING", (0, 0), (-1, -1), 3),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
                ("LEFTPADDING", (0, 0), (-1, -1), 4),
                ("RIGHTPADDING", (0, 0), (-1, -1), 4),
            ])
        )
        story.append(t_f)
        story.append(Spacer(1, 10))

    if "cbom" in selected:
        story.append(safe_p("Cryptographic Bill of Materials (CBOM) Summary", styles["SectionHeading"]))
        story.append(
            safe_p(
                f"Total Cryptographic Components: <b>{data.cbom_component_count}</b> discovered in this scan.",
                styles["BodyText"],
            )
        )

    doc.build(story, canvasmaker=NumberedCanvas)
    return buf.getvalue()
